# Databricks notebook source
# MAGIC %sql
# MAGIC use catalog gen_ai_am;
# MAGIC use schema ajay_db;

# COMMAND ----------

# MAGIC %sql
# MAGIC create table if not exists docs_text(id bigint generated by default as identity, text string) tblproperties(delta.enableChangeDataFeed=True);

# COMMAND ----------

# MAGIC %sql
# MAGIC create table if not exists docs_track (file_name string) tblproperties(delta.enableChangeDataFeed=True);